modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}"
license="MIT"

[[mods]] #mandatory
modId="elytrathrusters"
version="${file.jarVersion}"
displayName="Elytra Thrusters"
authors="Zorn_Taov, RobotGryphon" #optional
description="It's all so thrusty!"

issueTrackerURL="https://github.com/ZornTaov/ElytraThrusters/issues"

#updateJSONURL="http://myurl.me/" #optional
displayURL="https://github.com/ZornTaov/ElytraThrusters"

# A file name (in the root of the mod JAR) containing a logo for display
# logoFile="examplemod.png" #optional

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.elytrathrusters]] #optional
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.elytrathrusters]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"